#index:
#    path: /
#    controller: App\Controller\DefaultController::index
register:
    path: /getall
    controller: App\Controller\Api\EventosController::getAll
    methods: [GET]

api_login_check:
    path: /api/login
    methods:  [POST]
